### ISSUE TITLE
bug: provider default formatting incorrect

### ISSUE THREAD

**Issue by mkoryak** [CaryLandholt/ng-classify#36]
you have
```coffee
provider:
  format: 'camelCase'
  suffix: 'Provider'
```

So if I create a provider like this `class Foo extends Provider` ng-classify will register it as `fooProvider`, but angular will register it as `fooProviderProvider` because it also appends `Provider` to provider names!

You can try this yourself, create a provider with default settings and try to inject it as `fooProvider` - it will not be found.

**Comment by CaryLandholt** [comment]
Hi Misha,

I could have sworn I fixed this, but obviously not.

I'll fix it for sure now.  :)

Thanks,
Cary

**Comment by CaryLandholt** [comment]
Duplicate of https://github.com/CaryLandholt/ng-classify/pull/33
That PR failed to to failing unit test.
