### ISSUE TITLE
feat: add option that allows you to wrap/transform the class being registered

### ISSUE THREAD

**Issue by mkoryak** [CaryLandholt/ng-classify#37]
It would be very useful to us to be able to add new methods, etc to controllers (and perhaps services/factories) that are being registered with angular. 

I propose changing this lib the property DI style: `MyController.$inject = ['$scope', 'greeter'];` so that this  can also be transformed, then provide an option to transform all classes:

```coffee
controller:
  format: 'camelCase'
  suffix: 'Controller'
  transform: (className, obj) ->  obj
```

i realize that this would mean that this same transform function would have to be included in all the boiler plate code output by ng-classify - this kind of sucks, but maybe I can just attach that transform function on to window.angular or find some other optimization. Even without the optimization, I think this provides us with a great way to solve some cross cutting issues at a small cost of file size

**Comment by CaryLandholt** [comment]
Sorry, @mkoryak, I'm not following your request.

Can you explain in a different way?

Thanks

**Comment by mkoryak** [comment]
This is a pretty contrived example, but lets say I wanted all of my controllers to have 2 methods on them:
`@getFoo()` and `@setFoo()`

one way to do this would be by making ng-classify add those on there before it registers the controller with angular:

```
controller:
  format: 'camelCase'
  suffix: 'Controller'
  transform: (className, obj) ->  
    foo = 'bar'
    obj.getFoo = -> foo
    obj.setFoo = (_foo) -> foo = _foo 
    obj
```

then ng-classify would output code like this:

```
var controllerTransform = function(className, obj){
	var foo;
	foo = 'bar';
	obj.getFoo = function() {
	  return foo;
	};
	obj.setFoo = function(_foo) {
	  return foo = _foo;
	};
	return obj;
}
angular.module('bar').controller('AwesomeController', ['ProjectDraft', 'e', 'user', controllerTransform('AwesomeController', Marketing)]);
```

**Comment by mkoryak** [comment]
actually, this isnt a good idea :)

**Comment by CaryLandholt** [comment]
lol
