### ISSUE TITLE
Support for Browserify

### ISSUE THREAD

**Issue by Clever-Coding** [CaryLandholt/ng-classify#38]
I'm currently creating an Angular app in CoffeeScript and I use Browserify for module loading, the problem is that it doesn't work with ng-classify, so I thought that this could be possible:

before:

```coffeescript
module.export = class Admin extends Controller
  constructor: ($scope) ->
```

ng-classified:

```coffeescript
class Admin
  constructor: ($scope) ->

module.export = angular.module('app').controller 'adminController', ['$scope', Admin]

**Comment by CaryLandholt** [comment]
```coffee
module.export = angular.module('app').controller 'adminController', ['$scope', Admin]
```
will only return angular, not the class
the invocation of the function will register it (`adminController`, in this case) with angular

Unless I'm missing something, which may certainly be the case, the following is equivalent to your mentioned ng-classified version.

```coffee
class Admin extends Controller
  constructor: ($scope) ->

angular.module('app').controller 'adminController', ['$scope', Admin]

module.export = angular
```

What exactly do you want exported from ng-classify - let me ask it that way?

Thanks

**Comment by Clever-Coding** [comment]
Well, I want to be able to use the controller(and all ther other features) in any other CommonJS module in my app.

**Comment by CaryLandholt** [comment]
I understand CommonJS, but the thing is, angular encapsulates all module registration.
So has soon as you do something like
```coffee
angular.module('app').controller 'adminController', ['$scope', Admin]
```
angular has registered `adminController`.

There's really nothing to export, since angular is controlling the lifecycle of all dependencies.

The mere fact that your code is executed, all is registered.  Browserify will work.

I hope this makes sense.

**Comment by Clever-Coding** [comment]
Alright!

Thank you so much for answering, I'm still a little bit new to Angular :)

**Comment by CaryLandholt** [comment]
No worries.  Please don't hesitate to reach out again.

Cary
