### ISSUE TITLE
AngularJS 1.4

### ISSUE THREAD

**Issue by sebastiannm** [CaryLandholt/ng-classify#40]
Hi,

It looks like ng-classify breaks with the latest version of angular. I think that it's a error related to the nature of coffee-script.

With the new Angular, for example a directive returns the last function in the Directive

```
class Some extends Directive

    constructor: ->
        return {

            controller: ($scope) ->
                $scope.someFunction = ->
        }

```

That will return the function $scope.someFunction and not the whole directive for some reason. But if returning the directive at the end then it works

```
class Some extends Directive

    constructor: ->
        return {

            controller: ($scope) ->
                $scope.someFunction = ->

                return
        }

```

**Comment by CaryLandholt** [comment]
Hi @sebastiannm,

This is actually the same behavior prior to 1.4.

The preferred and recommended approach is to create a class for the controller and reference it from the directive configuration.

For example:

```coffeescript
class SomeDirective extends Controller
  constructor: ($scope, anotherDependency) ->
    $scope.someFunction = ->
      # code here
```

```coffeescript
class Some extends Directive
  constructor: ->
    return {
      controller: 'someDirectiveController'
    }
```

This has two benefits.
1. dependency management for the controller
2. isolation for improved unit testing

The above compiles to:
```javascript
(function() {
  var Some, SomeDirective;

  SomeDirective = (function() {
    function SomeDirective($scope, anotherDependency) {
      $scope.someFunction = function() {};
    }

    return SomeDirective;

  })();

  Some = (function() {
    function Some() {
      return {
        controller: 'someDirectiveController'
      };
    }

    return Some;

  })();

  angular.module('app').controller('someDirectiveController', ['$scope', 'anotherDependency', SomeDirective]).directive('some', [Some]);

}).call(this);
```

**Comment by sebastiannm** [comment]
The weird thing is that I have been using the controller inside the directive without problems until now.

I will try your solution

**Comment by CaryLandholt** [comment]
@sebastiannm please reopen if you are still having trouble.
Thanks
