### ISSUE TITLE
add a CLI

### ISSUE THREAD

**Issue by mkoryak** [CaryLandholt/ng-classify#41]
It would be good if this tool had a CLI. I can write one and PR it, the only thing that id like feedback on is how you would like the options to translate into arguments. Im thinking something like

```bash
./ngclassify --controller-format=camel --controller-suffix=Poop --value-format=none app-name=my.app ./input.coffee ./output.js 
```

**Comment by CaryLandholt** [comment]
Hi @mkoryak,

The camel poop made me laugh.  lol

It's an interesting question.  Can you sure the use case for an ng-classify CLI?

**Comment by mkoryak** [comment]
Heh, I opened this issue so long ago, I dont remember why exactly I needed this. Im sure it would be useful, but I don't have for a PR. 

On a completely unrelated note, I made this:
https://github.com/HourlyNerd/ng-classifyfy

you can include it your 'build tool integration' under 'browerserify' if you want. The name is weird because it is their standard to name transforms with `[what it does]fy` and so we get a `fyfy` :P

**Comment by CaryLandholt** [comment]
Cool, I'll take a look.  Thanks
