### ISSUE TITLE
Provider 'xxx' must return a value from $get factory method.

### ISSUE THREAD

**Issue by rlrhett** [CaryLandholt/ng-classify#43]
I'm trying to "classify" an existing angular factory, and I am not sure I understand what this is telling me.   This is how it was originally written in coffeescript:

```coffeescript
'use strict';

angular.module('App')
.factory 'Data', [
  '$log'
  '$q'
  ($log, $q) -> 

    openDB : ->
      db = new PouchDB 'myDB'
      return db

    getDB: ->
      db = $q.defer()
      db = @openDB()
      db.allDocs {include_docs: true}, (err, res) ->
        if err
          $log.log err
          db.resolve err
        else
          db.resolve res.rows
      return db.promise

#[and so on]
```
It goes on in the same vein with all the usual CRUD functions like findRecord, addRecord, etc.  It works fine, but I wanted to "classify" this code to better encapsulate it for future reuse.

this is how I rewrote it:

```coffeescript
class Data extends Factory
  constructor: ($log, $q) ->
    openDB : ->
      db = new PouchDB 'myDB'
      return db

    getDB: ->
      db = $q.defer()
      db = @openDB()
      db.allDocs {include_docs: true}, (err, res) ->
        if err
          $log.log err
          db.resolve err
        else
          db.resolve res.rows
      return db.promise

#[and so on]

```

However, I am getting the following error:

```
 Provider 'Data' must return a value from $get factory method.
```

I'm not sure I understand what is going wrong, and the examples in the API reference do not show a factory with more than one method.  Can you help me understand how the classify utility would handle this?

**Comment by rlrhett** [comment]
I have figured it out for myself.  You MUST add an explicit return object for the constructor function.  You cannot rely on the coffee script editor's implicit return.  The code should read:

```coffeescript
class Data extends Factory
  constructor: ($log, $q) ->
    return {
      openDB : ->
        db = new PouchDB 'myDB'
        return db
    #[and so on]
    }
```

**Comment by CaryLandholt** [comment]
hi @rlrhett, yep.  CoffeeScript usually returns the last line automatically, but with a class constructor function, it does not.  :)

You got it.
