### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by benaubin** [CaryLandholt/ng-classify#49]
I would like bower support, so I can more easily use this with rails (https://rails-assets.org) - the rails gem is out of date, and even if it is updated, it will most likely not be updated in the future. This makes rails-usage much easy.

I made a pull request for this, you can accept it to allow

```
bower install ng-classify
```

or in rails:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-ng-classify', '~> X.X'
end
```

 Thanks!

**Comment by benaubin** [comment]
Actually, let me propose a pull request...

**Comment by nmehta6** [comment]
@penne12 You could also install using git tags. For instance: `bower install https://github.com/CaryLandholt/ng-classify.git#4.1.1`.

**Comment by benaubin** [comment]
@nmehta6 doesn't work well with https://rails-assets.org

**Comment by CaryLandholt** [comment]
Hi @penne12.  Interesting, I hadn't heard of rails-assets before your mentioning it.

I'm assuming I'll need to create the bower package, register with bower.io, and register with rails-assets, is that correct?

**Comment by benaubin** [comment]
@CaryLandholt Yeah - that's correct, although now that I understand how ng-classify works, I don't think it would be smart to add it to bower, since bower is more for front-end dependencies.

**Comment by CaryLandholt** [comment]
ok - thanks for the clarification.

Yeah, ng-classify needs to be part of the build system.  In my rails apps, I use https://rubygems.org/gems/ng_classify.  Works great.

Thanks,
Cary

**Comment by benaubin** [comment]
@CaryLandholt yup - saw that - at first I though ng-classify was client side. I'm really loving it - migrated (almost) all of an old plain HTML/JS/CSS angular app to Rails, and I'm loving Coffeescript with ng-classify - thanks so much :smiley:

**Comment by CaryLandholt** [comment]
Cool!

**Comment by marcelinhov2** [comment]
Try angular-kickoff. It's awesome.
Em 24 de jan de 2016 11:55 PM, "Cary Landholt" notifications@github.com
escreveu:

**Comment by CaryLandholt** [comment]
thanks @marcelinhov2
